"""Initial migration.

Revision ID: 9356f9884124
Revises: 
Create Date: 2024-07-25 13:13:20.860292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9356f9884124'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('main1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main1',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hero_h1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('hero_h2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('products_h1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('products_item1_h1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('products_item1_p', sa.TEXT(), nullable=True),
    sa.Column('products_item2_h1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('products_item2_p', sa.TEXT(), nullable=True),
    sa.Column('products_item3_h1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('products_item3_p', sa.TEXT(), nullable=True),
    sa.Column('products_item4_h1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('products_item4_p', sa.TEXT(), nullable=True),
    sa.Column('about_h1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('about_p', sa.VARCHAR(length=255), nullable=True),
    sa.Column('about_cntc_c1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('about_cntc_c2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('about_cntc_l1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('about_cntc_l2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('about_cntc_hp', sa.VARCHAR(length=255), nullable=True),
    sa.Column('value_h1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('value_item1_h', sa.VARCHAR(length=255), nullable=True),
    sa.Column('value_item1_p', sa.TEXT(), nullable=True),
    sa.Column('value_item2_h', sa.VARCHAR(length=255), nullable=True),
    sa.Column('value_item2_p', sa.TEXT(), nullable=True),
    sa.Column('value_item3_h', sa.VARCHAR(length=255), nullable=True),
    sa.Column('value_item3_p', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    op.drop_table('product')
    # ### end Alembic commands ###
